//
// automatically generated by spin2cpp v1.91 on Thu Jun 19 14:20:30 2014
// ../spin2cpp --ccode HMC5883L_demo.spin 
//

#ifndef FullDuplexSerial_Class_Defined__
#define FullDuplexSerial_Class_Defined__

#include <stdint.h>


typedef struct FullDuplexSerial {
// cog flag/id
  volatile int32_t	cog;
// 9 contiguous longs
  volatile int32_t	rx_head;
  volatile int32_t	rx_tail;
  volatile int32_t	tx_head;
  volatile int32_t	tx_tail;
  volatile int32_t	rx_pin;
  volatile int32_t	tx_pin;
  volatile int32_t	rxtx_mode;
  volatile int32_t	bit_ticks;
  volatile int32_t	buffer_ptr;
// transmit and receive buffers
  volatile uint8_t	rx_buffer[16];
  volatile uint8_t	tx_buffer[16];
} FullDuplexSerial;

  int32_t FullDuplexSerial_start( FullDuplexSerial *self, int32_t rxpin, int32_t txpin, int32_t mode, int32_t baudrate);
  int32_t FullDuplexSerial_stop( FullDuplexSerial *self );
  int32_t FullDuplexSerial_rxflush( FullDuplexSerial *self );
  int32_t FullDuplexSerial_rxcheck( FullDuplexSerial *self );
  int32_t FullDuplexSerial_rxtime( FullDuplexSerial *self, int32_t ms);
  int32_t FullDuplexSerial_rx( FullDuplexSerial *self );
  int32_t FullDuplexSerial_tx( FullDuplexSerial *self, int32_t txbyte);
  int32_t FullDuplexSerial_str( FullDuplexSerial *self, int32_t stringptr);
  int32_t FullDuplexSerial_dec( FullDuplexSerial *self, int32_t value);
  int32_t FullDuplexSerial_hex( FullDuplexSerial *self, int32_t value, int32_t digits);
  int32_t FullDuplexSerial_bin( FullDuplexSerial *self, int32_t value, int32_t digits);
#endif
