//
// automatically generated by spin2cpp v1.91 on Thu Jun 19 14:20:30 2014
// ../spin2cpp --ccode HMC5883L_demo.spin 
//

#ifndef HMC5883L_demo_Class_Defined__
#define HMC5883L_demo_Class_Defined__

#include <stdint.h>
#include "FullDuplexSerial.h"
#include "SL32_INTEngine_2.h"

#define _clkmode ((8 + 1024))
#define _clkfreq (80000000)
// SDA
#define datapin (1)
// SCL
#define clockPin (0)
// All available registers on the HMC5883 are listed below: (Check datasheet for detailed information)
// Used to perform a Write operation
#define WRITE_DATA (60)
// Used to perform a Read operation
#define READ_DATA (61)
// Read/Write Register, Sets Data Output Rate. Default = 15Hz & 8 samples per measurement 
#define CNFG_A (0)
// 160Hz can be achieved by monitoring DRDY pin in single measurement mode.
// Read/Write Register, Sets the Device Gain(230-1370 Gauss). Default = 1090 Gauss
#define CNFG_B (1)
// Read/Write Register, Selects the operating mode. Default = Single measurement
#define MODE (2)
// Send $3C $02 $00 on power up to change to continuous measurement mode.         
// Read Register, Output of X MSB 8-bit value. (Will read -4096 if math overflow during bias measurement)
#define OUTPUT_X_MSB (3)
// Read Register, Output of X LSB 8-bit value. (Will read -4096 if math overflow during bias measurement)
#define OUTPUT_X_LSB (4)
// Read Register, Output of Z MSB 8-bit value. (Will read -4096 if math overflow during bias measurement)
#define OUTPUT_Z_MSB (5)
// Read Register, Output of Z LSB 8-bit value. (Will read -4096 if math overflow during bias measurement)
#define OUTPUT_Z_LSB (6)
// Read Register, Output of Y MSB 8-bit value. (Will read -4096 if math overflow during bias measurement)
#define OUTPUT_Y_MSB (7)
// Read Register, Output of Y LSB 8-bit value. (Will read -4096 if math overflow during bias measurement)
#define OUTPUT_Y_LSB (8)
// Read Register, indicates device status. 
#define STATUS (9)
// Read Register, (ASCII value H)              
#define ID_A (10)
// Read Register, (ASCII value 4)              
#define ID_B (11)
// Read Register, (ASCII value 3)
#define ID_C (12)

typedef struct HMC5883L_demo {
  int32_t	x;
  int32_t	y;
  int32_t	z;
  uint8_t	NE;
  uint8_t	SE;
  uint8_t	SW;
  uint8_t	NW;
  FullDuplexSerial	Term;
  SL32_INTEngine_2	math;
} HMC5883L_demo;

  int32_t HMC5883L_demo_Main( HMC5883L_demo *self );
  int32_t HMC5883L_demo_HeadingTerm( HMC5883L_demo *self );
  int32_t HMC5883L_demo_AzimuthTerm( HMC5883L_demo *self );
  int32_t HMC5883L_demo_RawTerm( HMC5883L_demo *self );
  int32_t HMC5883L_demo_aziadjust( HMC5883L_demo *self );
  int32_t HMC5883L_demo_Heading( HMC5883L_demo *self );
  int32_t HMC5883L_demo_SetCont( HMC5883L_demo *self );
  int32_t HMC5883L_demo_SetPointer( HMC5883L_demo *self, int32_t Register);
  int32_t HMC5883L_demo_GetRaw( HMC5883L_demo *self );
#endif
