//
// automatically generated by spin2cpp v1.91 on Thu Jun 19 14:20:30 2014
// ../spin2cpp --ccode HMC5883L_demo.spin 
//

#ifndef SL32_INTEngine_2_Class_Defined__
#define SL32_INTEngine_2_Class_Defined__

#include <stdint.h>


typedef struct SL32_INTEngine_2 {
  char dummy__;
} SL32_INTEngine_2;

  int32_t SL32_INTEngine_2_sin( SL32_INTEngine_2 *self, int32_t angle, int32_t radius);
  int32_t SL32_INTEngine_2_cos( SL32_INTEngine_2 *self, int32_t angle, int32_t radius);
  int32_t SL32_INTEngine_2_tan( SL32_INTEngine_2 *self, int32_t angle, int32_t radius);
  int32_t SL32_INTEngine_2_arcSin( SL32_INTEngine_2 *self, int32_t yLength, int32_t radius);
  int32_t SL32_INTEngine_2_arcCos( SL32_INTEngine_2 *self, int32_t xLength, int32_t radius);
  int32_t SL32_INTEngine_2_arcTan( SL32_INTEngine_2 *self, int32_t yLength, int32_t xLength);
  int32_t SL32_INTEngine_2_polarAngle( SL32_INTEngine_2 *self, int32_t yLength, int32_t xLength);
  int32_t SL32_INTEngine_2_polarRadius( SL32_INTEngine_2 *self, int32_t yLength, int32_t xLength);
  int32_t SL32_INTEngine_2_power( SL32_INTEngine_2 *self, int32_t base, int32_t exponent);
  int32_t SL32_INTEngine_2_random( SL32_INTEngine_2 *self, int32_t seedValue, int32_t maxValue, int32_t minValue);
#endif
 